### ISSUE TITLE
ElasticSearch - score boost for full phrase in results first

### ISSUE THREAD

**Issue by digitalWestie** [Mike-Heneghan/ALISS#31]
Research how we can achieve this.
Then try out different scoring methods.

**Comment by Mike-Heneghan** [comment]
When searching my local db of services noticed that after selecting "By best keyword match" if the search is selected again it reverts back to "By nearest first". I'm not sure whether or not this is deliberate although it could be confusing that the choice is taken from the user and they have to think about selecting "By best keyword match" again.

**Comment by Mike-Heneghan** [comment]
From the ElasticSearch docs: 

Best fields
When searching for words that represent a concept, such as “brown fox,” the words mean more together than they do individually. Fields like the title and body, while related, can be considered to be in competition with each other. Documents should have as many words as possible in the same field, and the score should come from the best-matching field.

We are already using "Best Fields" so I'm suprised the phrases aren't being handled better as the words in the term are "words mean more together than they do individually". Although this maybe just checks they are both in the field rather than being in the form as they appear in the query.

**Comment by Mike-Heneghan** [comment]
Best fields has an optional tie breaker parameter although it takes into account the scores in other fields rather than just th ebest match so would not improve the score of phrases.

**Comment by Mike-Heneghan** [comment]
Docs on proximity relevance: https://www.elastic.co/guide/en/elasticsearch/guide/current/proximity-relevance.html

From the research I’ve done so far our current setup with Multi-Match and Best-Fields with boosts on some fields is the best for our application. 

The options to have the positions as relevant don’t seem to be compatible with fuzziness as they tend to only return docs where the words come up and are too prohibitive.

**Comment by Mike-Heneghan** [comment]
On my local db it is hard to recreate the issues which were experienced by some aliss users. @digitalWestie when you get the chance could you please send the postcode and term which had issues so I can replicate it on my local dev db?

**Comment by digitalWestie** [comment]
There have been some developments on this so hold off the EA stuff for now

**Comment by Mike-Heneghan** [comment]
Could the issue potentially be with users expecting the keyword search to take precedence over how near it is? In which case maybe there is a way of making it clearer the results are ordered by location first? Or change the default sort to "By best keyword match". 

When I was trying to replicate the issue the initial result was unexpected but sorting by "By best keyword match" resolved it.
