### ISSUE TITLE
Indicate password requirements on sign up form

### ISSUE THREAD

**Issue by digitalWestie** [Mike-Heneghan/ALISS#42]
Just a sentence beneath password. Perhaps check django user docs for confirmation it's just 8 characters required.

**Comment by Mike-Heneghan** [comment]
Need to add the password requirements somewhere logical.

<img width="733" alt="screenshot 2019-02-18 at 17 34 58" src="https://user-images.githubusercontent.com/36415632/52967937-98ef0d80-33a3-11e9-8f6e-d76d5286014a.png">

**Comment by Mike-Heneghan** [comment]
Finding it hard to pin down the password requirements although it seems to be a minimum of 8 characters.

**Comment by Mike-Heneghan** [comment]
Trying to do a bit of research for user experience best practices with password creation. 

https://www.nngroup.com/articles/password-creation/

**Comment by Mike-Heneghan** [comment]
Tried to use the error style boxes to give the password requirements although struggling to unpick the way it's being handled.

**Comment by Mike-Heneghan** [comment]
Experimented with trying to update the signup model password input fields to change the behaviour.
```
    password1 = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput(attrs={
            'autocomplete': 'new-password',
        }),
        help_text='Minimum of 8 characters.',
    )
```

Unfortunately, the help_text isn't appearing. Need to continue experimenting.

**Comment by Mike-Heneghan** [comment]
Managed to get the help_text to display the password requirements as below:

<img width="740" alt="screenshot 2019-02-21 at 09 35 29" src="https://user-images.githubusercontent.com/36415632/53158691-2147fb00-35bc-11e9-9060-154ff90fc99f.png">

The password requirements may not be obvious although if they appear when the user selects the field it might be clearer? 

Also the autocomplete could is annoying because it autofills the postcode field withmy email address and a single blanked password. If the user is creating a new account they shouldn't have any autocomplete information?

**Comment by Mike-Heneghan** [comment]
Before the user clicks or tabs to the password field.

<img width="737" alt="screenshot 2019-02-21 at 10 45 35" src="https://user-images.githubusercontent.com/36415632/53163397-e1861100-35c5-11e9-86bf-182639a36f3e.png">

After the user click or tabs to the password field.

<img width="743" alt="screenshot 2019-02-21 at 10 45 46" src="https://user-images.githubusercontent.com/36415632/53163413-e945b580-35c5-11e9-95a0-de8007275b9d.png">

Had to add help_text to both fields otherwise the formatting was off. 

Also found that the help_text was clearer when above, oterwise it would be obscured by the autofill.

Also used `.focus()` rather than `.click()` as tabbing by accessibilty users wouldn't show the password requirements.

**Comment by Mike-Heneghan** [comment]
With autocomplete settings unchanged:

<img width="748" alt="screenshot 2019-02-21 at 11 23 44" src="https://user-images.githubusercontent.com/36415632/53165692-43954500-35cb-11e9-91f3-8fb38884f408.png">

With new password setting as below:

 ```   
widget=forms.PasswordInput(attrs={
            'autocomplete': 'new-password',
        }),
```

<img width="809" alt="screenshot 2019-02-21 at 11 24 19" src="https://user-images.githubusercontent.com/36415632/53165704-498b2600-35cb-11e9-9a17-e162455af502.png">

I think this is a usability improvement as erroneously having the email in the postcode field is confusing as well as a hidden password populating which the user has to overwrite.

**Comment by Mike-Heneghan** [comment]
Merger into master.
